페이지 이동 시 로그인 유지하기
coding-kkanbu/teameet_front pull request #7
Opened 2022-02-14 11:17 UTC by Szzng

- 로그인 기능을 AppBar로부터 분리하여 LogIn.vue 컴포넌트로 이동
- 로그인 상태와 관련된 변수를 vuex 저장소로 이동
- jwt 인증 방식을 적용하여 token이 있다고 가정하고 local storage에 token을 저장하며 로그인을 처리하는 코드 추가

2022-02-14 14:03 UTC, teacherSsamko requested changes

2022-02-14 14:03 UTC, teacherSsamko commented on src/components/LogIn.vue
> +      const postData = new FormData(document.getElementById('login-form'))
이건 vue답지 못하고 vanilla 스러운걸..? 그치만 여기선 문제 없어보인다!

2022-02-14 14:03 UTC, teacherSsamko commented on src/store/modules/userStore.js
> +      console.log('dialogOpen', kind)
이 console.log들은 배포시에는 다 삭제해야해. 아니면 vue-logger를 써서 환경별로 출력여부를 다르게 할 수 있고!

2022-02-14 14:03 UTC, teacherSsamko commented on src/store/modules/userStore.js
> +}
localStorage에서 토큰도 삭제해줘야지

2022-02-14 14:10 UTC, Szzng commented on src/store/modules/userStore.js
> +      console.log('dialogOpen', kind)
이거는 백엔드랑 연결까지 완료하고 완전히 다 확인한 후에 한 번에 싹 지우려고!

2022-02-14 14:19 UTC, Szzng commented on src/components/LogIn.vue
> +      const postData = new FormData(document.getElementById('login-form'))
바닐라?? 이거 뷰티파이 문서 보고 그냥 될 것 같아서 해봤는데 되길래 썼는데 뭐가 이상한가???

2022-02-15 15:24 UTC, teacherSsamko commented on src/components/LogIn.vue
> +      const postData = new FormData(document.getElementById('login-form'))
그래? vuetify문서에서도 저렇게 document.getElementById써서 해?? vue에서는 보통 v-model써서 하는거같아서~

2022-02-15 15:24 UTC, teacherSsamko approved these changes

2022-02-15 15:24 UTC, merged